In [1]:
!dir

 El volumen de la unidad C no tiene etiqueta.
 El n£mero de serie del volumen es: E45F-AAB0

 Directorio de C:\Users\emili\Documents\UP\8vo Semestre\Robotica Industrial

30/03/2020  17:09    <DIR>          .
30/03/2020  17:09    <DIR>          ..
30/03/2020  17:09    <DIR>          .ipynb_checkpoints
02/03/2020  18:16           278,975 Clusters.ipynb
24/02/2020  19:04             5,222 Formulario sin t¡tulo (respuestas).xlsx
27/01/2020  17:21             4,705 FuncionesMod.ipynb.zip
10/02/2020  20:16           107,350 Graficar funciones explicitamente.ipynb
10/02/2020  18:45         3,920,676 Graficar.ipynb
09/03/2020  18:41            64,557 Integraci¢n.ipynb
02/03/2020  17:17           171,188 Linear Regressions.ipynb
02/03/2020  18:25             2,132 Logistic Regression.ipynb
17/02/2020  18:48            13,947 Maximizar y minimizar funciones.ipynb
17/02/2020  19:50            26,724 Modelado de ecuaciones diferenciales.ipynb
30/03/2020  16:40           106,960 titanic3.csv
30/03/

In [3]:
import os 
import pandas as pd
import numpy as np

In [5]:
dataset_path = os.path.join('titanic3.csv')
titanic = pd.read_csv(dataset_path)
print(titanic.columns)

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')


In [6]:
titanic.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [7]:
titanic.shape

(1309, 14)

In [8]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [10]:
labels = titanic.survived.values
labels

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
features = titanic[['pclass', 'sex', 'age', 'sibsp', 'parch',
       'fare', 'embarked']]
features.head()

pclass     sex      age  sibsp  parch      fare embarked
0       1  female  29.0000      0      0  211.3375        S
1       1    male   0.9167      1      2  151.5500        S
2       1  female   2.0000      1      2  151.5500        S
3       1    male  30.0000      1      2  151.5500        S
4       1  female  25.0000      1      2  151.5500        S

In [13]:
pd.get_dummies(features).head()

pclass      age  sibsp  parch      fare  sex_female  sex_male  embarked_C  \
0       1  29.0000      0      0  211.3375           1         0           0   
1       1   0.9167      1      2  151.5500           0         1           0   
2       1   2.0000      1      2  151.5500           1         0           0   
3       1  30.0000      1      2  151.5500           0         1           0   
4       1  25.0000      1      2  151.5500           1         0           0   

   embarked_Q  embarked_S  
0           0           1  
1           0           1  
2           0           1  
3           0           1  
4           0           1

In [15]:
features_dummies = pd.get_dummies(features, columns=['pclass','sex','embarked'])
features_dummies.head()

age  sibsp  parch      fare  pclass_1  pclass_2  pclass_3  sex_female  \
0  29.0000      0      0  211.3375         1         0         0           1   
1   0.9167      1      2  151.5500         1         0         0           0   
2   2.0000      1      2  151.5500         1         0         0           1   
3  30.0000      1      2  151.5500         1         0         0           0   
4  25.0000      1      2  151.5500         1         0         0           1   

   sex_male  embarked_C  embarked_Q  embarked_S  
0         0           0           0           1  
1         1           0           0           1  
2         0           0           0           1  
3         1           0           0           1  
4         0           0           0           1

In [16]:
features_dummies.isna().any() #visualizar las celdas vacias

age            True
sibsp         False
parch         False
fare           True
pclass_1      False
pclass_2      False
pclass_3      False
sex_female    False
sex_male      False
embarked_C    False
embarked_Q    False
embarked_S    False
dtype: bool

In [22]:
features_dummies_train = features_dummies.dropna()
features_dummies_train.isna().any()
labels_train = labels[features_dummies_train.index]

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
model = LogisticRegression(solver='lbfgs',max_iter=500)

In [23]:
model.fit(features_dummies_train,labels_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
labels_train

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
model.predict(features_dummies_train)

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [28]:
sum(model.predict(features_dummies_train) == labels_train) / (len(labels_train))

0.7923444976076555

In [30]:
print("logistic regression score: %f" % model.score(features_dummies_train,labels_train)) #porcentaje de confiabilidad

logistic regression score: 0.792344


In [31]:
#Split into train and test sets

from sklearn.model_selection import train_test_split


In [32]:
train_data, test_data, train_labels, test_labels = train_test_split(features_dummies_train, labels_train, random_state=0,test_size=0.33)

In [33]:
train_data.shape, test_data.shape

((700, 12), (345, 12))

In [34]:
train_labels.shape, test_labels.shape

((700,), (345,))

In [38]:
features = titanic[['pclass', 'sex', 'age', 'sibsp', 'parch',
       'fare', 'embarked']]

features = pd.get_dummies(features, columns=['pclass','sex','embarked'])

features = features.dropna()

labels = labels[features.index]

train_data, test_data, train_labels, test_labels = train_test_split(features, labels_train, random_state=0,test_size=0.33)

model = LogisticRegression(solver='lbfgs',max_iter=500).fit(train_data,train_labels)

print("logistic regression score: %f" % model.score(test_data,test_labels))

IndexError: index 1045 is out of bounds for axis 0 with size 1045